version: 0.1.{build}
image: Visual Studio 2017

build_script:
   - git submodule update --init --recursive
   - 
   - mkdir build
   - cd build
   - cmake -G"Visual Studio 15 2017 Win64" -DBSZENLIB_DOWNLOAD_BSF_BINARIES=On -DCMAKE_BUILD_TYPE=Release ..
   - cmake --build . --config Release -j 4
   - 
   - cp -r bsf-binaries/bin/* bin/Release
   - 7z a BsZenLib.zip bin/
   - 
   - mv BsZenLib.zip BsZenLib-%appveyor_repo_branch%-%APPVEYOR_BUILD_VERSION%-win32.zip
   - appveyor PushArtifact BsZenLib-%appveyor_repo_branch%-%APPVEYOR_BUILD_VERSION%-win32.zip

